@echo off
set DEST=.\.exvim.react
set TOOLS=D:\exVim\vimfiles\tools\
set FILE_SUFFIXS=
set GAWK_SUFFIX=exc
set FILE_FILTER_PATTERN=""
set FOLDER_FILTER_PATTERN=".*\\\\node_modules\\\\.*"
set TMP=%DEST%\_files_gawk
set TMP2=%DEST%\_files
set TARGET=%DEST%\files
set ID_TARGET="%DEST%\idutils-files"
call %TOOLS%\shell\batch\update-filelist.bat
